definitions:
  task:
       properties:
         Title:
           type: string
         Description:
           type: string
         Status:
           type: integer
         Created:
           type: string
         DueDate:
           type: string
         CompletionDate:
           type: string
         Completed:
           type: boolean
             